name: Check Links

on:
  schedule:
    - cron: '0 15 * * *'  # 每天北京时间23点（UTC+8）
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests tenacity

      - name: Run link checker
        run: python src/check_links.py

      - name: Run link recovery
        run: python src/recover_links.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src/links.json src/link-dead.json
          git commit -m "Auto update link status" || echo "No changes to commit"
          git push
